=== ezstaking/app-registry/chains/chain.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "title": "EZ Staking App Registry",
  "description": "EZ Staking App Registry",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "$schema",
    "name",
    "chainName",
    "logo_URIs",
    "rpcUrl",
    "restUrl",
    "chainId",
    "denom",
    "denomUpper",
    "sdenom",
    "coinType",
    "gasPriceStep",
    "coinDecimals",
    "features",
    "coinGeckoId",
    "chainInfo",
    "colors",
    "links",
    "isExplorerEnabled",
    "isModuleEnabled",
    "isNativelySupportedByKeplr",
    "withCoingeckoApi",
    "isFeatured"
  ],
  "properties": {
    "$schema": {
      "type": "string",
      "enum": [
        "../../chain.schema.json"
      ]
    },
    "name": {
      "type": "string"
    },
    "chainName": {
      "type": "string"
    },
    "shortChainName": {
      "type": "string"
    },
    "logo_URIs": {
      "$ref": "#/$defs/logo"
    },
    "rpcUrl": {
      "$ref": "#/$defs/url"
    },
    "restUrl": {
      "$ref": "#/$defs/url"
    },
    "chainId": {
      "type": "string"
    },
    "consumerId": {
      "type": "string",
      "description": "Only required for consumer chain."
    },
    "bech32": {
      "type": "string"
    },
    "denom": {
      "type": "string"
    },
    "denomUpper": {
      "type": "string"
    },
    "sdenom": {
      "type": "string"
    },
    "bech32PrefixAcc": {
      "type": "string"
    },
    "bech32PrefixVal": {
      "type": "string"
    },
    "coinType": {
      "type": "number"
    },
    "gasPriceStep": {
      "type": "object"
    },
    "coinDecimals": {
      "type": "number"
    },
    "features": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "ibc-transfer",
          "ibc-go",
          "cosmwasm",
          "wasmd_0.24+",
          "eth-address-gen",
          "eth-key-sign",
          "secretwasm"
        ]
      }
    },
    "coinGeckoId": {
      "type": [
        "string",
        "null"
      ]
    },
    "assets": {
      "$ref": "#/$defs/assets"
    },
    "chainInfo": {
      "$ref": "#/$defs/chainInfo"
    },
    "colors": {
      "$ref": "#/$defs/colors"
    },
    "links": {
      "$ref": "#/$defs/links"
    },
    "isExplorerEnabled": {
      "type": "boolean"
    },
    "isModuleEnabled": {
      "$ref": "#/$defs/isModuleEnabled"
    },
    "isAProviderChain": {
      "type": "boolean"
    },
    "isAConsumerChain": {
      "type": "boolean"
    },
    "providerChain": {
      "type": "string"
    },
    "gasModifier": {
      "description": "If the gas calculation is wrong, you can change the multiplier.",
      "type": "number",
      "default": 1.3
    },
    "isNativelySupportedByKeplr": {
      "description": "Allow to add the chain in Keplr.",
      "type": "boolean"
    },
    "withCoingeckoApi": {
      "description": "If we validate your chain, we'll take care of the API ourselves. If not, don't hesitate to provide us with an API key: contact[@]ezstaking[.]io.",
      "type": "boolean",
      "default": false
    },
    "isFeatured": {
      "description": "True if we validate your chain.",
      "type": "boolean",
      "default": false
    }
  },
  "$defs": {
    "url": {
      "type": "string"
    },
    "assets": {
      "description": "Required only for assets that's not in the Cosmos Chain Registry.",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "base": {
            "type": "string"
          },
          "coingecko_id": {
            "type": [
              "string",
              "null"
            ]
          },
          "denom_units": {
            "type": "array"
          },
          "description": {
            "type": "string"
          },
          "display": {
            "type": "string"
          },
          "logo_URIs": {
            "$ref": "#/$defs/logo"
          },
          "name": {
            "type": "string"
          },
          "symbol": {
            "type": "string"
          }
        },
        "required": [
          "base",
          "coingecko_id",
          "denom_units",
          "description",
          "display",
          "logo_URIs",
          "name",
          "symbol"
        ],
        "additionalProperties": false
      }
    },
    "chainInfo": {
      "type": "object",
      "required": [
        "cosmosSdkVersion",
        "ibcGoVersion"
      ],
      "properties": {
        "cosmosSdkVersion": {
          "$ref": "#/$defs/semver"
        },
        "ibcGoVersion": {
          "$ref": "#/$defs/semver"
        }
      },
      "additionalProperties": false
    },
    "colors": {
      "type": "object",
      "required": [
        "primaryOnLight",
        "primaryOnDark",
        "lighterOnLight",
        "lighterOnDark",
        "darkerOnLight",
        "darkerOnDark"
      ],
      "properties": {
        "primaryOnLight": {
          "description": "Primary color for light theme.",
          "type": "string"
        },
        "primaryOnDark": {
          "description": "Primary color for dark theme.",
          "type": "string"
        },
        "lighterOnLight": {
          "description": "Lighter color than the primary one and for light theme.",
          "type": "string"
        },
        "lighterOnDark": {
          "description": "Lighter color than the primary one and for dark theme.",
          "type": "string"
        },
        "darkerOnLight": {
          "description": "Darker color than the primary one and for light theme.",
          "type": "string"
        },
        "darkerOnDark": {
          "description": "Darker color than the primary one and for dark theme.",
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "logo": {
      "type": "object",
      "properties": {
        "png": {
          "$ref": "#/$defs/url"
        },
        "svg": {
          "$ref": "#/$defs/url"
        }
      },
      "additionalProperties": false
    },
    "image": {
      "type": "object",
      "oneOf": [
        {
          "type": "object",
          "properties": {
            "url": {
              "$ref": "#/$defs/url"
            }
          },
          "additionalProperties": false
        },
        {
          "type": "object",
          "properties": {
            "svg": {
              "type": "string"
            }
          },
          "additionalProperties": false
        },
        {
          "type": "object",
          "properties": {
            "svgImg": {
              "type": "string"
            }
          },
          "additionalProperties": false
        },
        {
          "type": "object",
          "properties": {
            "font": {
              "type": "string"
            }
          },
          "additionalProperties": false
        }
      ]
    },
    "link": {
      "type": "object",
      "required": [
        "url",
        "title",
        "icon"
      ],
      "properties": {
        "url": {
          "$ref": "#/$defs/url"
        },
        "title": {
          "type": "string"
        },
        "icon": {
          "$ref": "#/$defs/image"
        }
      },
      "additionalProperties": false
    },
    "childLinks": {
      "type": "object",
      "required": [
        "title",
        "icon",
        "children"
      ],
      "properties": {
        "title": {
          "type": "string"
        },
        "icon": {
          "type": "object",
          "$ref": "#/$defs/image"
        },
        "children": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/link"
          },
          "minItems": 1
        }
      },
      "additionalProperties": false
    },
    "links": {
      "type": "array",
      "items": {
        "oneOf": [
          {
            "$ref": "#/$defs/link"
          },
          {
            "$ref": "#/$defs/childLinks"
          }
        ]
      },
      "minItems": 4,
      "maxItems": 4,
      "uniqueItems": true
    },
    "isModuleEnabled": {
      "type": "object",
      "required": [
        "governance"
      ],
      "properties": {
        "governance": {
          "type": "boolean"
        }
      },
      "additionalProperties": false
    },
    "semver": {
      "type": "string",
      "minLength": 5,
      "maxLength": 14,
      "pattern": "^(?:0|[1-9]\\d*)\\.(?:0|[1-9]\\d*)\\.(?:0|[1-9]\\d*)$"
    }
  }
}

=== ezstaking/app-registry/public/chains/mainnets/cudos/chain.json
{
  "$schema": "../../chain.schema.json",
  "name": "cudos",
  "chainName": "Cudos",
  "logo_URIs": {
    "png": "https://raw.githubusercontent.com/cosmos/chain-registry/master/cudos/images/cudos.png",
    "svg": "https://raw.githubusercontent.com/cosmos/chain-registry/master/cudos/images/cudos.svg"
  },
  "rpcUrl": "http://mainnet-full-node-01.hosts.cudos.org:26657",
  "restUrl": "http://mainnet-full-node-01.hosts.cudos.org:1317",
  "chainId": "cudos-1",
  "bech32": "cudos",
  "denom": "cudos",
  "denomUpper": "CUDOS",
  "sdenom": "acudos",
  "coinType": 118,
  "coinDecimals": 18,
  "features": [
    "ibc-transfer"
  ],
  "coinGeckoId": "cudos",
  "gasPriceStep": {
    "low": 5000000000000,
    "average": 10000000000000,
    "high": 20000000000000
  },
  "chainInfo": {
    "cosmosSdkVersion": "0.45.3",
    "ibcGoVersion": "2.2.0"
  },
  "colors": {
    "primaryOnLight": "#10aecc",
    "primaryOnDark": "#10aecc",
    "lighterOnLight": "#10aecc",
    "lighterOnDark": "#10aecc",
    "darkerOnLight": "#10aecc",
    "darkerOnDark": "#10aecc"
  },
  "links": [
    {
      "title": "Official Website",
      "url": "https://www.cudos.org/",
      "icon": {
        "svg": "web"
      }
    },
    {
      "title": "Docs",
      "url": "https://docs.cudos.org",
      "icon": {
        "svg": "document"
      }
    },
    {
      "title": "GitHub",
      "url": "https://github.com/CudoVentures/cudos-eth-token-contract",
      "icon": {
        "svg": "github"
      }
    },
    {
      "title": "Learn more",
      "icon": {
        "svg": "dotsHorizontal"
      },
      "children": [
        {
          "title": "Medium",
          "url": "https://medium.com/cudos",
          "icon": {
            "svg": "medium"
          }
        },
        {
          "title": "Twitter",
          "url": "https://twitter.com/cudos_",
          "icon": {
            "svg": "twitter"
          }
        }
      ]
    }
  ],
  "isExplorerEnabled": true,
  "isModuleEnabled": {
    "governance": true
  },
  "isNativelySupportedByKeplr": false,
  "withCoingeckoApi": false,
  "isFeatured": false
}

=== ezstaking/app-registry/chains/mainnets/shentu/chain.json
{
  "$schema": "../../chain.schema.json",
  "name": "shentu",
  "chainName": "Shentu",
  "logo_URIs": {
    "png": "https://raw.githubusercontent.com/cosmos/chain-registry/master/shentu/images/ctk.png",
    "svg": "https://raw.githubusercontent.com/cosmos/chain-registry/master/shentu/images/ctk.svg"
  },
  "rpcUrl": "https://rpc.cosmos.directory/shentu",
  "restUrl": "https://rest.cosmos.directory/shentu",
  "chainId": "shentu-2.2",
  "bech32": "shentu",
  "denom": "ctk",
  "denomUpper": "CTK",
  "sdenom": "uctk",
  "coinType": 118,
  "gasPriceStep": {
    "low": 0.025,
    "average": 0.025,
    "high": 0.025
  },
  "coinDecimals": 6,
  "features": [],
  "coinGeckoId": "certik",
  "chainInfo": {
    "cosmosSdkVersion": "0.47.10",
    "ibcGoVersion": "7.4.0"
  },
  "colors": {
    "primaryOnLight": "#e1aa4c",
    "primaryOnDark": "#e1aa4c",
    "lighterOnLight": "#f8f2e9",
    "lighterOnDark": "#f8f2e9",
    "darkerOnLight": "#e1aa4c",
    "darkerOnDark": "#e1aa4c"
  },
  "links": [
    {
      "title": "Official Website",
      "url": "https://shentu.technology",
      "icon": {
        "svg": "web"
      }
    },
    {
      "title": "GitHub",
      "url": "https://github.com/ShentuChain",
      "icon": {
        "svg": "github"
      }
    },
    {
      "title": "Medium",
      "url": "https://medium.com/shentu-foundation",
      "icon": {
        "svg": "medium"
      }
    },
    {
      "title": "Learn more",
      "icon": {
        "svg": "dotsHorizontal"
      },
      "children": [
        {
          "title": "Twitter",
          "url": "https://twitter.com/ShentuChain",
          "icon": {
            "svg": "twitter"
          }
        },
        {
          "title": "Discord",
          "url": "https://discord.com/invite/7D62sHx6aZ",
          "icon": {
            "svg": "discord"
          }
        }
      ]
    }
  ],
  "isExplorerEnabled": true,
  "isModuleEnabled": {
    "governance": true
  },
  "isNativelySupportedByKeplr": true,
  "withCoingeckoApi": false,
  "isFeatured": false
}

=== ezstaking/app-registry/chains/mainnets/kujira/chain.json
{
  "$schema": "../../chain.schema.json",
  "name": "kujira",
  "chainName": "Kujira",
  "logo_URIs": {
    "png": "https://raw.githubusercontent.com/cosmos/chain-registry/master/kujira/images/kujira-chain-logo.png",
    "svg": "https://raw.githubusercontent.com/cosmos/chain-registry/master/kujira/images/kuji.svg"
  },
  "rpcUrl": "https://rpc.cosmos.directory/kujira",
  "restUrl": "https://rest.cosmos.directory/kujira",
  "chainId": "kaiyo-1",
  "bech32": "kujira",
  "denom": "kuji",
  "denomUpper": "KUJI",
  "sdenom": "ukuji",
  "coinType": 118,
  "gasPriceStep": {
    "low": 0.0034,
    "average": 0.0051,
    "high": 0.00681
  },
  "coinDecimals": 6,
  "features": [
    "ibc-transfer"
  ],
  "coinGeckoId": "kujira",
  "chainInfo": {
    "cosmosSdkVersion": "0.47.12",
    "ibcGoVersion": "7.3.0"
  },
  "colors": {
    "primaryOnLight": "#e53935",
    "primaryOnDark": "#e53935",
    "lighterOnLight": "#ededed",
    "lighterOnDark": "#ededed",
    "darkerOnLight": "#e53935",
    "darkerOnDark": "#e53935"
  },
  "links": [
    {
      "title": "Official Website",
      "url": "https://kujira.app/",
      "icon": {
        "svg": "web"
      }
    },
    {
      "title": "Docs",
      "url": "https://docs.kujira.app/introduction/readme",
      "icon": {
        "svg": "document"
      }
    },
    {
      "title": "GitHub",
      "url": "https://github.com/Team-Kujira",
      "icon": {
        "svg": "github"
      }
    },
    {
      "title": "Learn more",
      "icon": {
        "svg": "dotsHorizontal"
      },
      "children": [
        {
          "title": "Medium",
          "url": "https://medium.com/team-kujira",
          "icon": {
            "svg": "medium"
          }
        },
        {
          "title": "Twitter",
          "url": "https://twitter.com/TeamKujira",
          "icon": {
            "svg": "twitter"
          }
        },
        {
          "title": "Discord",
          "url": "https://discord.com/invite/teamkujira",
          "icon": {
            "svg": "discord"
          }
        }
      ]
    }
  ],
  "isExplorerEnabled": true,
  "isModuleEnabled": {
    "governance": true
  },
  "isNativelySupportedByKeplr": false,
  "withCoingeckoApi": false,
  "isFeatured": false
}

=== ezstaking/app-registry/chains/mainnets/quicksilver/chain.json
{
  "$schema": "../../chain.schema.json",
  "name": "quicksilver",
  "chainName": "Quicksilver",
  "logo_URIs": {
    "png": "https://raw.githubusercontent.com/cosmos/chain-registry/master/quicksilver/images/qck.png",
    "svg": "https://raw.githubusercontent.com/cosmos/chain-registry/master/quicksilver/images/qck.svg"
  },
  "rpcUrl": "https://rpc.cosmos.directory/quicksilver",
  "restUrl": "https://rest.cosmos.directory/quicksilver",
  "chainId": "quicksilver-2",
  "bech32": "quick",
  "denom": "qck",
  "denomUpper": "QCK",
  "sdenom": "uqck",
  "coinType": 118,
  "coinDecimals": 6,
  "features": [
    "ibc-transfer"
  ],
  "coinGeckoId": "quicksilver",
  "gasPriceStep": {
    "low": 0.0001,
    "average": 0.0001,
    "high": 0.00025
  },
  "chainInfo": {
    "cosmosSdkVersion": "0.46.16",
    "ibcGoVersion": "6.3.1"
  },
  "colors": {
    "primaryOnLight": "#9b9b9b",
    "primaryOnDark": "#9b9b9b",
    "lighterOnLight": "#9b9b9b",
    "lighterOnDark": "#9b9b9b",
    "darkerOnLight": "#9b9b9b",
    "darkerOnDark": "#9b9b9b"
  },
  "links": [
    {
      "title": "Official Website",
      "url": "https://quicksilver.zone/",
      "icon": {
        "svg": "web"
      }
    },
    {
      "title": "Docs",
      "url": "https://quicksilver.zone/whitepaper.pdf",
      "icon": {
        "svg": "document"
      }
    },
    {
      "title": "GitHub",
      "url": "https://github.com/ingenuity-build/quicksilver",
      "icon": {
        "svg": "github"
      }
    },
    {
      "title": "Learn more",
      "icon": {
        "svg": "dotsHorizontal"
      },
      "children": [
        {
          "title": "Medium",
          "url": "https://medium.com/quicksilverzone",
          "icon": {
            "svg": "medium"
          }
        },
        {
          "title": "Twitter",
          "url": "https://twitter.com/quicksilverzone",
          "icon": {
            "svg": "twitter"
          }
        }
      ]
    }
  ],
  "isExplorerEnabled": true,
  "isModuleEnabled": {
    "governance": true
  },
  "isNativelySupportedByKeplr": true,
  "withCoingeckoApi": false,
  "isFeatured": false
}

=== ezstaking/app-registry/chains/mainnets/irisnet/chain.json
{
  "$schema": "../../chain.schema.json",
  "name": "irisnet",
  "chainName": "IRISnet",
  "logo_URIs": {
    "png": "https://raw.githubusercontent.com/cosmos/chain-registry/master/irisnet/images/iris.png",
    "svg": "https://raw.githubusercontent.com/cosmos/chain-registry/master/irisnet/images/iris.svg"
  },
  "rpcUrl": "https://rpc.irishub-1.irisnet.org",
  "restUrl": "https://api.irishub-1.irisnet.org",
  "chainId": "irishub-1",
  "denom": "iris",
  "denomUpper": "IRIS",
  "sdenom": "uiris",
  "bech32PrefixAcc": "iaa",
  "bech32PrefixVal": "iva",
  "coinType": 118,
  "gasPriceStep": {
    "low": 0.0025,
    "average": 0.0025,
    "high": 0.0025
  },
  "coinDecimals": 6,
  "features": [],
  "coinGeckoId": "iris-network",
  "chainInfo": {
    "cosmosSdkVersion": "0.47.4",
    "ibcGoVersion": "7.3.0"
  },
  "colors": {
    "primaryOnLight": "#0492dc",
    "primaryOnDark": "#0492dc",
    "darkerOnLight": "#0492dc",
    "darkerOnDark": "#0492dc",
    "lighterOnLight": "#e0f2fb",
    "lighterOnDark": "#e0f2fb"
  },
  "links": [
    {
      "title": "Official Website",
      "url": "https://www.irisnet.org",
      "icon": {
        "svg": "web"
      }
    },
    {
      "title": "Docs",
      "url": "https://www.irisnet.org/docs",
      "icon": {
        "svg": "document"
      }
    },
    {
      "title": "GitHub",
      "url": "https://github.com/irisnet",
      "icon": {
        "svg": "github"
      }
    },
    {
      "title": "Learn more",
      "icon": {
        "svg": "dotsHorizontal"
      },
      "children": [
        {
          "title": "Medium",
          "url": "https://medium.com/irisnet-blog",
          "icon": {
            "svg": "medium"
          }
        },
        {
          "title": "Twitter",
          "url": "https://twitter.com/irisnetwork",
          "icon": {
            "svg": "twitter"
          }
        }
      ]
    }
  ],
  "isExplorerEnabled": true,
  "isModuleEnabled": {
    "governance": true
  },
  "isNativelySupportedByKeplr": true,
  "withCoingeckoApi": true,
  "isFeatured": true
}

=== ezstaking/app-registry/public/chains/mainnets/noble/chain.json
{
  "$schema": "../../chain.schema.json",
  "name": "noble",
  "chainName": "Noble",
  "logo_URIs": {
    "png": "https://raw.githubusercontent.com/cosmos/chain-registry/master/noble/images/stake.png",
    "svg": "https://raw.githubusercontent.com/cosmos/chain-registry/master/noble/images/stake.svg"
  },
  "rpcUrl": "https://rpc.cosmos.directory/noble",
  "restUrl": "https://rest.cosmos.directory/noble",
  "chainId": "noble-1",
  "bech32": "noble",
  "denom": "stake",
  "denomUpper": "STAKE",
  "sdenom": "ustake",
  "coinType": 118,
  "coinDecimals": 6,
  "features": [
    "ibc-transfer"
  ],
  "coinGeckoId": "",
  "gasPriceStep": {
    "low": 0.1,
    "average": 0.1,
    "high": 0.2
  },
  "chainInfo": {
    "cosmosSdkVersion": "0.45.16",
    "ibcGoVersion": "4.5.1"
  },
  "colors": {
    "primaryOnLight": "#6A8AF8",
    "primaryOnDark": "#6A8AF8",
    "lighterOnLight": "#6A8AF8",
    "lighterOnDark": "#6A8AF8",
    "darkerOnLight": "#6A8AF8",
    "darkerOnDark": "#6A8AF8"
  },
  "links": [
    {
      "title": "Official Website",
      "url": "https://nobleassets.xyz/",
      "icon": {
        "svg": "web"
      }
    },
    {
      "title": "Twitter",
      "url": "https://twitter.com/noble_xyz",
      "icon": {
        "svg": "twitter"
      }
    },
    {
      "title": "GitHub",
      "url": "https://github.com/strangelove-ventures/noble",
      "icon": {
        "svg": "github"
      }
    },
    {
      "title": "Learn more",
      "icon": {
        "svg": "dotsHorizontal"
      },
      "children": [
        {
          "title": "Medium",
          "url": "https://mirror.xyz/nobleassets.eth",
          "icon": {
            "svg": "medium"
          }
        }
      ]
    }
  ],
  "isExplorerEnabled": true,
  "isModuleEnabled": {
    "governance": false
  },
  "isNativelySupportedByKeplr": true,
  "withCoingeckoApi": false,
  "isFeatured": false
}

=== ezstaking/app-registry/chains/mainnets/kichain/chain.json
{
  "$schema": "../../chain.schema.json",
  "name": "kichain",
  "chainName": "KiChain",
  "logo_URIs": {
    "png": "https://raw.githubusercontent.com/cosmos/chain-registry/master/kichain/images/xki.png",
    "svg": "https://raw.githubusercontent.com/cosmos/chain-registry/master/kichain/images/xki.svg"
  },
  "rpcUrl": "https://rpc-mainnet.blockchain.ki",
  "restUrl": "https://api-mainnet.blockchain.ki",
  "chainId": "kichain-2",
  "denom": "xki",
  "denomUpper": "XKI",
  "sdenom": "uxki",
  "bech32": "ki",
  "coinType": 118,
  "gasPriceStep": {
    "low": 0.025,
    "average": 0.025,
    "high": 0.025
  },
  "coinDecimals": 6,
  "features": [
    "ibc-transfer",
    "cosmwasm"
  ],
  "coinGeckoId": "ki",
  "chainInfo": {
    "cosmosSdkVersion": "0.45.12",
    "ibcGoVersion": "3.3.1"
  },
  "colors": {
    "primaryOnLight": "#3756fc",
    "primaryOnDark": "#3756fc",
    "lighterOnLight": "#eaeaea",
    "lighterOnDark": "#eaeaea",
    "darkerOnLight": "#3756fc",
    "darkerOnDark": "#3756fc"
  },
  "links": [
    {
      "title": "Official Website",
      "url": "https://foundation.ki",
      "icon": {
        "svg": "web"
      }
    },
    {
      "title": "DApp",
      "icon": {
        "svg": "apps"
      },
      "children": [
        {
          "title": "Cosmon",
          "url": "https://cosmon.ki/",
          "icon": {
            "svgImg": "dapp/cosmon"
          }
        }
      ]
    },
    {
      "title": "GitHub",
      "url": "https://github.com/KiFoundation",
      "icon": {
        "svg": "github"
      }
    },
    {
      "title": "Learn more",
      "icon": {
        "svg": "dotsHorizontal"
      },
      "children": [
        {
          "title": "Medium",
          "url": "https://medium.com/ki-foundation",
          "icon": {
            "svg": "medium"
          }
        },
        {
          "title": "Twitter",
          "url": "https://twitter.com/Ki_Foundation",
          "icon": {
            "svg": "twitter"
          }
        }
      ]
    }
  ],
  "isExplorerEnabled": true,
  "isModuleEnabled": {
    "governance": true
  },
  "isNativelySupportedByKeplr": false,
  "withCoingeckoApi": true,
  "isFeatured": true
}

=== ezstaking/app-registry/chains/mainnets/nois/chain.json
{
  "$schema": "../../chain.schema.json",
  "name": "nois",
  "chainName": "Nois",
  "logo_URIs": {
    "png": "https://raw.githubusercontent.com/cosmos/chain-registry/master/nois/images/nois.png"
  },
  "rpcUrl": "https://rpc-nois.ezstaking.dev",
  "restUrl": "https://lcd-nois.ezstaking.dev",
  "chainId": "nois-1",
  "bech32": "nois",
  "denom": "nois",
  "denomUpper": "NOIS",
  "sdenom": "unois",
  "coinType": 118,
  "gasPriceStep": {
    "low": 0.05,
    "average": 0.08,
    "high": 0.1
  },
  "coinDecimals": 6,
  "features": [
    "ibc-transfer",
    "ibc-go",
    "cosmwasm",
    "wasmd_0.24+"
  ],
  "coinGeckoId": "",
  "assets": [
    {
      "base": "unois",
      "coingecko_id": null,
      "denom_units": [
        {
          "denom": "unois",
          "exponent": 0
        },
        {
          "denom": "nois",
          "exponent": 6
        }
      ],
      "description": "The native staking and governance token of the Nois Network.",
      "display": "nois",
      "logo_URIs": {
        "png": "https://raw.githubusercontent.com/cosmos/chain-registry/master/nois/images/nois.png"
      },
      "name": "NOIS",
      "symbol": "NOIS"
    }
  ],
  "chainInfo": {
    "cosmosSdkVersion": "0.45.14",
    "ibcGoVersion": "4.3.0"
  },
  "colors": {
    "primaryOnLight": "#0B0914",
    "primaryOnDark": "#e5e7eb",
    "lighterOnLight": "#e5e7eb",
    "lighterOnDark": "#e5e7eb",
    "darkerOnLight": "#161130",
    "darkerOnDark": "#161130"
  },
  "links": [
    {
      "title": "Official Website",
      "url": "https://nois.network",
      "icon": {
        "svg": "web"
      }
    },
    {
      "title": "Docs",
      "url": "https://docs.nois.network",
      "icon": {
        "svg": "document"
      }
    },
    {
      "title": "GitHub",
      "url": "https://github.com/noislabs",
      "icon": {
        "svg": "github"
      }
    },
    {
      "title": "Learn more",
      "icon": {
        "svg": "dotsHorizontal"
      },
      "children": [
        {
          "title": "Twitter",
          "url": "https://twitter.com/NoisNetwork",
          "icon": {
            "svg": "twitter"
          }
        },
        {
          "title": "Discord",
          "url": "https://chat.nois.network",
          "icon": {
            "svg": "discord"
          }
        }
      ]
    }
  ],
  "isExplorerEnabled": true,
  "isModuleEnabled": {
    "governance": true
  },
  "isNativelySupportedByKeplr": false,
  "withCoingeckoApi": true,
  "isFeatured": true
}
