=== ezstaking/app-registry/chains/chain.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "title": "EZ Staking App Registry",
  "description": "EZ Staking App Registry",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "$schema",
    "name",
    "chainName",
    "logo_URIs",
    "rpcUrl",
    "restUrl",
    "chainId",
    "denom",
    "denomUpper",
    "sdenom",
    "coinType",
    "gasPriceStep",
    "coinDecimals",
    "features",
    "coinGeckoId",
    "chainInfo",
    "colors",
    "links",
    "isExplorerEnabled",
    "isModuleEnabled",
    "isNativelySupportedByKeplr",
    "withCoingeckoApi",
    "isFeatured"
  ],
  "properties": {
    "$schema": {
      "type": "string",
      "enum": [
        "../../chain.schema.json"
      ]
    },
    "name": {
      "type": "string"
    },
    "chainName": {
      "type": "string"
    },
    "shortChainName": {
      "type": "string"
    },
    "logo_URIs": {
      "$ref": "#/$defs/logo"
    },
    "rpcUrl": {
      "$ref": "#/$defs/url"
    },
    "restUrl": {
      "$ref": "#/$defs/url"
    },
    "chainId": {
      "type": "string"
    },
    "consumerId": {
      "type": "string",
      "description": "Only required for consumer chain."
    },
    "bech32": {
      "type": "string"
    },
    "denom": {
      "type": "string"
    },
    "denomUpper": {
      "type": "string"
    },
    "sdenom": {
      "type": "string"
    },
    "bech32PrefixAcc": {
      "type": "string"
    },
    "bech32PrefixVal": {
      "type": "string"
    },
    "coinType": {
      "type": "number"
    },
    "gasPriceStep": {
      "type": "object"
    },
    "coinDecimals": {
      "type": "number"
    },
    "features": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "ibc-transfer",
          "ibc-go",
          "cosmwasm",
          "wasmd_0.24+",
          "eth-address-gen",
          "eth-key-sign",
          "secretwasm"
        ]
      }
    },
    "coinGeckoId": {
      "type": [
        "string",
        "null"
      ]
    },
    "assets": {
      "$ref": "#/$defs/assets"
    },
    "chainInfo": {
      "$ref": "#/$defs/chainInfo"
    },
    "colors": {
      "$ref": "#/$defs/colors"
    },
    "links": {
      "$ref": "#/$defs/links"
    },
    "isExplorerEnabled": {
      "type": "boolean"
    },
    "isModuleEnabled": {
      "$ref": "#/$defs/isModuleEnabled"
    },
    "isAProviderChain": {
      "type": "boolean"
    },
    "isAConsumerChain": {
      "type": "boolean"
    },
    "providerChain": {
      "type": "string"
    },
    "gasModifier": {
      "description": "If the gas calculation is wrong, you can change the multiplier.",
      "type": "number",
      "default": 1.3
    },
    "isNativelySupportedByKeplr": {
      "description": "Allow to add the chain in Keplr.",
      "type": "boolean"
    },
    "withCoingeckoApi": {
      "description": "If we validate your chain, we'll take care of the API ourselves. If not, don't hesitate to provide us with an API key: contact[@]ezstaking[.]io.",
      "type": "boolean",
      "default": false
    },
    "isFeatured": {
      "description": "True if we validate your chain.",
      "type": "boolean",
      "default": false
    }
  },
  "$defs": {
    "url": {
      "type": "string"
    },
    "assets": {
      "description": "Required only for assets that's not in the Cosmos Chain Registry.",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "base": {
            "type": "string"
          },
          "coingecko_id": {
            "type": [
              "string",
              "null"
            ]
          },
          "denom_units": {
            "type": "array"
          },
          "description": {
            "type": "string"
          },
          "display": {
            "type": "string"
          },
          "logo_URIs": {
            "$ref": "#/$defs/logo"
          },
          "name": {
            "type": "string"
          },
          "symbol": {
            "type": "string"
          }
        },
        "required": [
          "base",
          "coingecko_id",
          "denom_units",
          "description",
          "display",
          "logo_URIs",
          "name",
          "symbol"
        ],
        "additionalProperties": false
      }
    },
    "chainInfo": {
      "type": "object",
      "required": [
        "cosmosSdkVersion",
        "ibcGoVersion"
      ],
      "properties": {
        "cosmosSdkVersion": {
          "$ref": "#/$defs/semver"
        },
        "ibcGoVersion": {
          "$ref": "#/$defs/semver"
        }
      },
      "additionalProperties": false
    },
    "colors": {
      "type": "object",
      "required": [
        "primaryOnLight",
        "primaryOnDark",
        "lighterOnLight",
        "lighterOnDark",
        "darkerOnLight",
        "darkerOnDark"
      ],
      "properties": {
        "primaryOnLight": {
          "description": "Primary color for light theme.",
          "type": "string"
        },
        "primaryOnDark": {
          "description": "Primary color for dark theme.",
          "type": "string"
        },
        "lighterOnLight": {
          "description": "Lighter color than the primary one and for light theme.",
          "type": "string"
        },
        "lighterOnDark": {
          "description": "Lighter color than the primary one and for dark theme.",
          "type": "string"
        },
        "darkerOnLight": {
          "description": "Darker color than the primary one and for light theme.",
          "type": "string"
        },
        "darkerOnDark": {
          "description": "Darker color than the primary one and for dark theme.",
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "logo": {
      "type": "object",
      "properties": {
        "png": {
          "$ref": "#/$defs/url"
        },
        "svg": {
          "$ref": "#/$defs/url"
        }
      },
      "additionalProperties": false
    },
    "image": {
      "type": "object",
      "oneOf": [
        {
          "type": "object",
          "properties": {
            "url": {
              "$ref": "#/$defs/url"
            }
          },
          "additionalProperties": false
        },
        {
          "type": "object",
          "properties": {
            "svg": {
              "type": "string"
            }
          },
          "additionalProperties": false
        },
        {
          "type": "object",
          "properties": {
            "svgImg": {
              "type": "string"
            }
          },
          "additionalProperties": false
        },
        {
          "type": "object",
          "properties": {
            "font": {
              "type": "string"
            }
          },
          "additionalProperties": false
        }
      ]
    },
    "link": {
      "type": "object",
      "required": [
        "url",
        "title",
        "icon"
      ],
      "properties": {
        "url": {
          "$ref": "#/$defs/url"
        },
        "title": {
          "type": "string"
        },
        "icon": {
          "$ref": "#/$defs/image"
        }
      },
      "additionalProperties": false
    },
    "childLinks": {
      "type": "object",
      "required": [
        "title",
        "icon",
        "children"
      ],
      "properties": {
        "title": {
          "type": "string"
        },
        "icon": {
          "type": "object",
          "$ref": "#/$defs/image"
        },
        "children": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/link"
          },
          "minItems": 1
        }
      },
      "additionalProperties": false
    },
    "links": {
      "type": "array",
      "items": {
        "oneOf": [
          {
            "$ref": "#/$defs/link"
          },
          {
            "$ref": "#/$defs/childLinks"
          }
        ]
      },
      "minItems": 4,
      "maxItems": 4,
      "uniqueItems": true
    },
    "isModuleEnabled": {
      "type": "object",
      "required": [
        "governance"
      ],
      "properties": {
        "governance": {
          "type": "boolean"
        }
      },
      "additionalProperties": false
    },
    "semver": {
      "type": "string",
      "minLength": 5,
      "maxLength": 14,
      "pattern": "^(?:0|[1-9]\\d*)\\.(?:0|[1-9]\\d*)\\.(?:0|[1-9]\\d*)$"
    }
  }
}

=== ezstaking/app-registry/chains/mainnets/persistence/chain.json
{
  "$schema": "../../chain.schema.json",
  "name": "persistence",
  "chainName": "Persistence",
  "logo_URIs": {
    "png": "https://raw.githubusercontent.com/cosmos/chain-registry/master/persistence/images/xprt.png",
    "svg": "https://raw.githubusercontent.com/cosmos/chain-registry/master/persistence/images/xprt.svg"
  },
  "rpcUrl": "https://rpc.core.persistence.one",
  "restUrl": "https://rest.core.persistence.one",
  "chainId": "core-1",
  "bech32": "persistence",
  "denom": "xprt",
  "denomUpper": "XPRT",
  "sdenom": "uxprt",
  "coinType": 118,
  "coinDecimals": 6,
  "features": [
    "ibc-transfer"
  ],
  "coinGeckoId": "persistence",
  "gasPriceStep": {
    "low": 0,
    "average": 0.025,
    "high": 0.04
  },
  "chainInfo": {
    "cosmosSdkVersion": "ersistenceOne/cosmos-sdk v0.47.10-lsm-rc0",
    "ibcGoVersion": "7.4.0"
  },
  "colors": {
    "primaryOnLight": "#e50a13",
    "primaryOnDark": "#e50a13",
    "lighterOnLight": "#e50a13",
    "lighterOnDark": "#e50a13",
    "darkerOnLight": "#e50a13",
    "darkerOnDark": "#e50a13"
  },
  "links": [
    {
      "title": "Official Website",
      "url": "https://persistence.one/",
      "icon": {
        "svg": "web"
      }
    },
    {
      "title": "Twitter",
      "url": "https://twitter.com/PersistenceOne",
      "icon": {
        "svg": "twitter"
      }
    },
    {
      "title": "GitHub",
      "url": "https://github.com/persistenceOne",
      "icon": {
        "svg": "github"
      }
    },
    {
      "title": "Learn more",
      "icon": {
        "svg": "dotsHorizontal"
      },
      "children": [
        {
          "title": "Medium",
          "url": "https://blog.persistence.one/",
          "icon": {
            "svg": "medium"
          }
        }
      ]
    }
  ],
  "isExplorerEnabled": true,
  "isModuleEnabled": {
    "governance": true
  },
  "isNativelySupportedByKeplr": true,
  "withCoingeckoApi": false,
  "isFeatured": false
}

=== ezstaking/app-registry/chains/mainnets/bitsong/chain.json
{
  "$schema": "../../chain.schema.json",
  "name": "bitsong",
  "chainName": "BitSong",
  "logo_URIs": {
    "png": "https://raw.githubusercontent.com/cosmos/chain-registry/master/bitsong/images/btsg.png",
    "svg": "https://raw.githubusercontent.com/cosmos/chain-registry/master/bitsong/images/btsg.svg"
  },
  "rpcUrl": "https://rpc.explorebitsong.com",
  "restUrl": "https://lcd.explorebitsong.com",
  "chainId": "bitsong-2b",
  "bech32": "bitsong",
  "denom": "btsg",
  "denomUpper": "BTSG",
  "sdenom": "ubtsg",
  "coinType": 639,
  "gasPriceStep": {
    "low": 0.015,
    "average": 0.015,
    "high": 0.015
  },
  "coinDecimals": 6,
  "features": ["ibc-transfer", "ibc-go", "cosmwasm", "wasmd_0.24+"],
  "coinGeckoId": "bitsong",
  "chainInfo": {
    "cosmosSdkVersion": "0.45.16",
    "ibcGoVersion": "3.3.1"
  },
  "colors": {
    "primaryOnLight": "#ff005c",
    "primaryOnDark": "#ff005c",
    "lighterOnLight": "#fbe9f1",
    "lighterOnDark": "#fbe9f1",
    "darkerOnLight": "#201a5e",
    "darkerOnDark": "#201a5e"
  },
  "links": [
    {
      "title": "Official Website",
      "url": "https://bitsong.io",
      "icon": {
        "svg": "web"
      }
    },
    {
      "title": "BitSong Music Player",
      "url": "https://play.bitsong.io",
      "icon": {
        "svg": "apps"
      }
    },
    {
      "title": "Docs",
      "url": "https://docs.bitsong.io",
      "icon": {
        "svg": "document"
      }
    },
    {
      "title": "Learn more",
      "icon": {
        "svg": "dotsHorizontal"
      },
      "children": [
        {
          "title": "GitHub",
          "url": "https://github.com/bitsongofficial",
          "icon": {
            "svg": "github"
          }
        },
        {
          "title": "Medium",
          "url": "https://bitsongofficial.medium.com",
          "icon": {
            "svg": "medium"
          }
        },
        {
          "title": "Twitter",
          "url": "https://twitter.com/bitsongofficial",
          "icon": {
            "svg": "twitter"
          }
        }
      ]
    }
  ],
  "isExplorerEnabled": true,
  "isModuleEnabled": {
    "governance": true
  },
  "isNativelySupportedByKeplr": false,
  "withCoingeckoApi": false,
  "isFeatured": false
}

=== ezstaking/app-registry/chains/mainnets/provenance/chain.json
{
  "$schema": "../../chain.schema.json",
  "name": "provenance",
  "chainName": "Provenance",
  "logo_URIs": {
    "png": "https://raw.githubusercontent.com/cosmos/chain-registry/master/provenance/images/prov.png",
    "svg": "https://raw.githubusercontent.com/cosmos/chain-registry/master/provenance/images/prov.svg"
  },
  "rpcUrl": "https://rpc.cosmos.directory/provenance",
  "restUrl": "https://rest.cosmos.directory/provenance",
  "chainId": "pio-mainnet-1",
  "bech32": "pb",
  "denom": "hash",
  "denomUpper": "HASH",
  "sdenom": "nhash",
  "coinType": 505,
  "coinDecimals": 9,
  "features": [
    "ibc-transfer"
  ],
  "coinGeckoId": "provenance-blockchain",
  "gasPriceStep": {
    "low": 1905,
    "average": 2100,
    "high": 2500
  },
  "chainInfo": {
    "cosmosSdkVersion": ".46.13",
    "ibcGoVersion": "1.0.1"
  },
  "colors": {
    "primaryOnLight": "#628ee4",
    "primaryOnDark": "#628ee4",
    "lighterOnLight": "#628ee4",
    "lighterOnDark": "#628ee4",
    "darkerOnLight": "#628ee4",
    "darkerOnDark": "#628ee4"
  },
  "links": [
    {
      "title": "Official Website",
      "url": "https://provenance.io/",
      "icon": {
        "svg": "web"
      }
    },
    {
      "title": "Docs",
      "url": "https://docs.provenance.io/",
      "icon": {
        "svg": "document"
      }
    },
    {
      "title": "GitHub",
      "url": "https://github.com/provenance-io",
      "icon": {
        "svg": "github"
      }
    },
    {
      "title": "Learn more",
      "icon": {
        "svg": "dotsHorizontal"
      },
      "children": [
        {
          "title": "Medium",
          "url": "https://medium.com/provenanceblockchain",
          "icon": {
            "svg": "medium"
          }
        },
        {
          "title": "Twitter",
          "url": "https://twitter.com/provenancefdn",
          "icon": {
            "svg": "twitter"
          }
        }
      ]
    }
  ],
  "isExplorerEnabled": true,
  "isModuleEnabled": {
    "governance": true
  },
  "isNativelySupportedByKeplr": false,
  "withCoingeckoApi": false,
  "isFeatured": false
}

=== ezstaking/app-registry/public/chains/testnets/babylon_testnet/chain.json
{
  "$schema": "../../chain.schema.json",
  "name": "babylon_testnet",
  "chainName": "Babylon Testnet",
  "logo_URIs": {
    "svg": "https://raw.githubusercontent.com/cosmos/chain-registry/master/testnets/babylontestnet/images/logo.svg"
  },
  "rpcUrl": "https://rpc-babylon.ezstaking.dev",
  "restUrl": "https://lcd-babylon.ezstaking.dev",
  "chainId": "bbn-test-3",
  "denom": "bbn",
  "denomUpper": "BBN",
  "sdenom": "ubbn",
  "bech32": "bbn",
  "coinType": 118,
  "gasPriceStep": {
    "low": 0.00001,
    "average": 0.00002,
    "high": 0.00003
  },
  "coinDecimals": 6,
  "features": ["ibc-transfer", "ibc-go", "cosmwasm"],
  "coinGeckoId": "",
  "assets": [
    {
      "base": "ubbn",
      "coingecko_id": null,
      "denom_units": [
        {
          "denom": "bbn",
          "exponent": 6
        },
        {
          "denom": "ubbn",
          "exponent": 0
        }
      ],
      "description": "The native staking token of Babylon.",
      "display": "bbn",
      "logo_URIs": {
        "svg": "https://raw.githubusercontent.com/cosmos/chain-registry/master/testnets/babylontestnet/images/logo.svg"
      },
      "name": "Babylon BBN",
      "symbol": "BBN"
    }
  ],
  "chainInfo": {
    "cosmosSdkVersion": "0.50.4",
    "ibcGoVersion": "1.0.0"
  },
  "colors": {
    "primaryOnLight": "#ff7c2b",
    "primaryOnDark": "#ff7c2b",
    "lighterOnLight": "#ff7c2b",
    "lighterOnDark": "#ff7c2b",
    "darkerOnLight": "#ff7c2b",
    "darkerOnDark": "#ff7c2b"
  },
  "links": [
    {
      "title": "Official Website",
      "url": "https://babylonchain.io",
      "icon": {
        "svg": "web"
      }
    },
    {
      "title": "Docs",
      "url": "https://docs.babylonchain.io",
      "icon": {
        "svg": "document"
      }
    },
    {
      "title": "GitHub",
      "url": "https://github.com/babylonchain",
      "icon": {
        "svg": "github"
      }
    },
    {
      "title": "Learn more",
      "icon": {
        "svg": "dotsHorizontal"
      },
      "children": [
        {
          "title": "Medium",
          "url": "https://medium.com/babylonchain-io",
          "icon": {
            "svg": "medium"
          }
        },
        {
          "title": "Twitter",
          "url": "https://twitter.com/babylon_chain",
          "icon": {
            "svg": "twitter"
          }
        },
        {
          "title": "Discord",
          "url": "https://discord.com/invite/babylonglobal?ezstakingapp",
          "icon": {
            "svg": "discord"
          }
        },
        {
          "title": "Telegram",
          "url": "https://t.me/babyloncommunity",
          "icon": {
            "svg": "telegram"
          }
        }
      ]
    }
  ],
  "isExplorerEnabled": true,
  "isModuleEnabled": {
    "governance": true
  },
  "isNativelySupportedByKeplr": false,
  "withCoingeckoApi": false,
  "isFeatured": false
}

=== ezstaking/app-registry/chains/mainnets/emoney/chain.json
{
  "$schema": "../../chain.schema.json",
  "name": "emoney",
  "chainName": "e-Money",
  "logo_URIs": {
    "png": "https://raw.githubusercontent.com/cosmos/chain-registry/master/emoney/images/ngm.png",
    "svg": "https://raw.githubusercontent.com/cosmos/chain-registry/master/emoney/images/ngm.svg"
  },
  "rpcUrl": "https://emoney.validator.network",
  "restUrl": "https://emoney.validator.network/api",
  "chainId": "emoney-3",
  "bech32": "emoney",
  "denom": "ngm",
  "denomUpper": "NGM",
  "sdenom": "ungm",
  "coinType": 118,
  "gasPriceStep": {
    "low": 0.025,
    "average": 0.025,
    "high": 0.025
  },
  "coinDecimals": 6,
  "features": [
    "ibc-transfer"
  ],
  "coinGeckoId": "e-money",
  "chainInfo": {
    "cosmosSdkVersion": "0.42.11",
    "ibcGoVersion": "3.0.0"
  },
  "colors": {
    "primaryOnLight": "#035059",
    "primaryOnDark": "#035059",
    "lighterOnLight": "#86ccba",
    "lighterOnDark": "#86ccba",
    "darkerOnLight": "#00282d",
    "darkerOnDark": "#00282d"
  },
  "links": [
    {
      "title": "Official Website",
      "url": "https://e-money.com",
      "icon": {
        "svg": "web"
      }
    },
    {
      "title": "e-Money Wallet",
      "url": "https://app.e-money.com",
      "icon": {
        "svg": "apps"
      }
    },
    {
      "title": "GitHub",
      "url": "https://github.com/e-money",
      "icon": {
        "svg": "github"
      }
    },
    {
      "title": "Learn more",
      "icon": {
        "svg": "dotsHorizontal"
      },
      "children": [
        {
          "title": "Medium",
          "url": "https://medium.com/e-money-com",
          "icon": {
            "svg": "medium"
          }
        },
        {
          "title": "Twitter",
          "url": "https://twitter.com/emoney_com",
          "icon": {
            "svg": "twitter"
          }
        }
      ]
    }
  ],
  "isExplorerEnabled": true,
  "isModuleEnabled": {
    "governance": false
  },
  "isNativelySupportedByKeplr": false,
  "withCoingeckoApi": false,
  "isFeatured": false
}

=== ezstaking/app-registry/chains/mainnets/stafihub/chain.json
{
  "$schema": "../../chain.schema.json",
  "name": "stafihub",
  "chainName": "StaFi Hub",
  "logo_URIs": {
    "svg": "https://raw.githubusercontent.com/cosmos/chain-registry/master/stafihub/images/fis.svg",
    "png": "https://raw.githubusercontent.com/cosmos/chain-registry/master/stafihub/images/stafihub-chain-logo.png"
  },
  "rpcUrl": "https://rpc.cosmos.directory/stafihub",
  "restUrl": "https://rest.cosmos.directory/stafihub",
  "chainId": "stafihub-1",
  "bech32": "stafi",
  "denom": "fis",
  "denomUpper": "FIS",
  "sdenom": "ufis",
  "coinType": 118,
  "coinDecimals": 6,
  "features": [
    "ibc-transfer"
  ],
  "coinGeckoId": "stafi",
  "gasPriceStep": {
    "low": 0,
    "average": 0.025,
    "high": 0.04
  },
  "chainInfo": {
    "cosmosSdkVersion": "0.46.14",
    "ibcGoVersion": "6.2.0"
  },
  "colors": {
    "primaryOnLight": "#6758ff",
    "primaryOnDark": "#6758ff",
    "lighterOnLight": "#6758ff",
    "lighterOnDark": "#6758ff",
    "darkerOnLight": "#6758ff",
    "darkerOnDark": "#6758ff"
  },
  "links": [
    {
      "title": "Official Website",
      "url": "https://stafihub.io/",
      "icon": {
        "svg": "web"
      }
    },
    {
      "title": "Docs",
      "url": "https://docs.stafihub.io/welcome-to-stafihub/",
      "icon": {
        "svg": "document"
      }
    },
    {
      "title": "GitHub",
      "url": "https://github.com/stafihub/stafihub",
      "icon": {
        "svg": "github"
      }
    },
    {
      "title": "Learn more",
      "icon": {
        "svg": "dotsHorizontal"
      },
      "children": [
        {
          "title": "Medium",
          "url": "https://stafi-protocol.medium.com/",
          "icon": {
            "svg": "medium"
          }
        },
        {
          "title": "Twitter",
          "url": "https://twitter.com/StaFiHub_",
          "icon": {
            "svg": "twitter"
          }
        }
      ]
    }
  ],
  "isExplorerEnabled": true,
  "isModuleEnabled": {
    "governance": true
  },
  "isNativelySupportedByKeplr": true,
  "withCoingeckoApi": false,
  "isFeatured": false
}

=== ezstaking/app-registry/chains/mainnets/assetmantle/chain.json
{
  "$schema": "../../chain.schema.json",
  "name": "assetmantle",
  "chainName": "AssetMantle",
  "logo_URIs": {
    "png": "https://raw.githubusercontent.com/cosmos/chain-registry/master/assetmantle/images/AM_Logo.png",
    "svg": "https://raw.githubusercontent.com/cosmos/chain-registry/master/assetmantle/images/AM_Logo_Dark.svg"
  },
  "rpcUrl": "https://rpc-assetmantle.ezstaking.dev",
  "restUrl": "https://lcd-assetmantle.ezstaking.dev",
  "chainId": "mantle-1",
  "bech32": "mantle",
  "denom": "mntl",
  "denomUpper": "MNTL",
  "sdenom": "umntl",
  "coinType": 118,
  "gasPriceStep": {
    "low": 0,
    "average": 0,
    "high": 0
  },
  "coinDecimals": 6,
  "features": ["ibc-transfer"],
  "coinGeckoId": "assetmantle",
  "chainInfo": {
    "cosmosSdkVersion": "0.45.16",
    "ibcGoVersion": "4.4.2"
  },
  "colors": {
    "primaryOnLight": "#f3b519",
    "primaryOnDark": "#f3b519",
    "lighterOnLight": "#f6f3e9",
    "lighterOnDark": "#f6f3e9",
    "darkerOnLight": "#f6f3e9",
    "darkerOnDark": "#f6f3e9"
  },
  "links": [
    {
      "title": "Official Website",
      "url": "https://assetmantle.one",
      "icon": {
        "svg": "web"
      }
    },
    {
      "title": "Docs",
      "url": "https://docs.assetmantle.one",
      "icon": {
        "svg": "document"
      }
    },
    {
      "title": "GitHub",
      "url": "https://github.com/AssetMantle",
      "icon": {
        "svg": "github"
      }
    },
    {
      "title": "Learn more",
      "icon": {
        "svg": "dotsHorizontal"
      },
      "children": [
        {
          "title": "Medium",
          "url": "https://blog.assetmantle.one",
          "icon": {
            "svg": "medium"
          }
        },
        {
          "title": "Twitter",
          "url": "https://twitter.com/AssetMantle",
          "icon": {
            "svg": "twitter"
          }
        }
      ]
    }
  ],
  "isExplorerEnabled": true,
  "isModuleEnabled": {
    "governance": true
  },
  "isNativelySupportedByKeplr": false,
  "withCoingeckoApi": true,
  "isFeatured": true
}

=== ezstaking/app-registry/chains/mainnets/chihuahua/chain.json
{
  "$schema": "../../chain.schema.json",
  "name": "chihuahua",
  "chainName": "Chihuahua",
  "logo_URIs": {
    "png": "https://raw.githubusercontent.com/cosmos/chain-registry/master/chihuahua/images/huahua.png",
    "svg": "https://raw.githubusercontent.com/cosmos/chain-registry/master/chihuahua/images/huahua.svg"
  },
  "rpcUrl": "https://rpc.chihuahua.wtf",
  "restUrl": "https://api.chihuahua.wtf",
  "chainId": "chihuahua-1",
  "denom": "huahua",
  "denomUpper": "HUAHUA",
  "bech32": "chihuahua",
  "sdenom": "uhuahua",
  "coinType": 118,
  "gasPriceStep": {
    "low": 0.0025,
    "average": 0.0025,
    "high": 0.0025
  },
  "coinDecimals": 6,
  "features": [
    "ibc-transfer",
    "ibc-go",
    "cosmwasm",
    "wasmd_0.24+"
  ],
  "coinGeckoId": "chihuahua-token",
  "chainInfo": {
    "cosmosSdkVersion": "0.47.5",
    "ibcGoVersion": "7.3.0"
  },
  "colors": {
    "primaryOnLight": "#f4b330",
    "primaryOnDark": "#f4b330",
    "lighterOnLight": "#f1f1f2",
    "lighterOnDark": "#f1f1f2",
    "darkerOnLight": "#f4b330",
    "darkerOnDark": "#f4b330"
  },
  "links": [
    {
      "title": "Official Website",
      "url": "https://www.chihuahua.wtf",
      "icon": {
        "svg": "web"
      }
    },
    {
      "title": "Docs",
      "url": "https://github.com/ChihuahuaChain/mainnet",
      "icon": {
        "svg": "document"
      }
    },
    {
      "title": "GitHub",
      "url": "https://github.com/ChihuahuaChain/mainnet",
      "icon": {
        "svg": "github"
      }
    },
    {
      "title": "Learn more",
      "icon": {
        "svg": "dotsHorizontal"
      },
      "children": [
        {
          "title": "Medium",
          "url": "https://chihuahuachain.medium.com",
          "icon": {
            "svg": "medium"
          }
        },
        {
          "title": "Twitter",
          "url": "https://twitter.com/ChihuahuaChain",
          "icon": {
            "svg": "twitter"
          }
        }
      ]
    }
  ],
  "isExplorerEnabled": true,
  "isModuleEnabled": {
    "governance": true
  },
  "isNativelySupportedByKeplr": true,
  "withCoingeckoApi": false,
  "isFeatured": false
}
