=== ezstaking/app-registry/chains/chain.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "title": "EZ Staking App Registry",
  "description": "EZ Staking App Registry",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "$schema",
    "name",
    "chainName",
    "logo_URIs",
    "rpcUrl",
    "restUrl",
    "chainId",
    "denom",
    "denomUpper",
    "sdenom",
    "coinType",
    "gasPriceStep",
    "coinDecimals",
    "features",
    "coinGeckoId",
    "chainInfo",
    "colors",
    "links",
    "isExplorerEnabled",
    "isModuleEnabled",
    "isNativelySupportedByKeplr",
    "withCoingeckoApi",
    "isFeatured"
  ],
  "properties": {
    "$schema": {
      "type": "string",
      "enum": [
        "../../chain.schema.json"
      ]
    },
    "name": {
      "type": "string"
    },
    "chainName": {
      "type": "string"
    },
    "shortChainName": {
      "type": "string"
    },
    "logo_URIs": {
      "$ref": "#/$defs/logo"
    },
    "rpcUrl": {
      "$ref": "#/$defs/url"
    },
    "restUrl": {
      "$ref": "#/$defs/url"
    },
    "chainId": {
      "type": "string"
    },
    "consumerId": {
      "type": "string",
      "description": "Only required for consumer chain."
    },
    "bech32": {
      "type": "string"
    },
    "denom": {
      "type": "string"
    },
    "denomUpper": {
      "type": "string"
    },
    "sdenom": {
      "type": "string"
    },
    "bech32PrefixAcc": {
      "type": "string"
    },
    "bech32PrefixVal": {
      "type": "string"
    },
    "coinType": {
      "type": "number"
    },
    "gasPriceStep": {
      "type": "object"
    },
    "coinDecimals": {
      "type": "number"
    },
    "features": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "ibc-transfer",
          "ibc-go",
          "cosmwasm",
          "wasmd_0.24+",
          "eth-address-gen",
          "eth-key-sign",
          "secretwasm"
        ]
      }
    },
    "coinGeckoId": {
      "type": [
        "string",
        "null"
      ]
    },
    "assets": {
      "$ref": "#/$defs/assets"
    },
    "chainInfo": {
      "$ref": "#/$defs/chainInfo"
    },
    "colors": {
      "$ref": "#/$defs/colors"
    },
    "links": {
      "$ref": "#/$defs/links"
    },
    "isExplorerEnabled": {
      "type": "boolean"
    },
    "isModuleEnabled": {
      "$ref": "#/$defs/isModuleEnabled"
    },
    "isAProviderChain": {
      "type": "boolean"
    },
    "isAConsumerChain": {
      "type": "boolean"
    },
    "providerChain": {
      "type": "string"
    },
    "gasModifier": {
      "description": "If the gas calculation is wrong, you can change the multiplier.",
      "type": "number",
      "default": 1.3
    },
    "isNativelySupportedByKeplr": {
      "description": "Allow to add the chain in Keplr.",
      "type": "boolean"
    },
    "withCoingeckoApi": {
      "description": "If we validate your chain, we'll take care of the API ourselves. If not, don't hesitate to provide us with an API key: contact[@]ezstaking[.]io.",
      "type": "boolean",
      "default": false
    },
    "isFeatured": {
      "description": "True if we validate your chain.",
      "type": "boolean",
      "default": false
    }
  },
  "$defs": {
    "url": {
      "type": "string"
    },
    "assets": {
      "description": "Required only for assets that's not in the Cosmos Chain Registry.",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "base": {
            "type": "string"
          },
          "coingecko_id": {
            "type": [
              "string",
              "null"
            ]
          },
          "denom_units": {
            "type": "array"
          },
          "description": {
            "type": "string"
          },
          "display": {
            "type": "string"
          },
          "logo_URIs": {
            "$ref": "#/$defs/logo"
          },
          "name": {
            "type": "string"
          },
          "symbol": {
            "type": "string"
          }
        },
        "required": [
          "base",
          "coingecko_id",
          "denom_units",
          "description",
          "display",
          "logo_URIs",
          "name",
          "symbol"
        ],
        "additionalProperties": false
      }
    },
    "chainInfo": {
      "type": "object",
      "required": [
        "cosmosSdkVersion",
        "ibcGoVersion"
      ],
      "properties": {
        "cosmosSdkVersion": {
          "$ref": "#/$defs/semver"
        },
        "ibcGoVersion": {
          "$ref": "#/$defs/semver"
        }
      },
      "additionalProperties": false
    },
    "colors": {
      "type": "object",
      "required": [
        "primaryOnLight",
        "primaryOnDark",
        "lighterOnLight",
        "lighterOnDark",
        "darkerOnLight",
        "darkerOnDark"
      ],
      "properties": {
        "primaryOnLight": {
          "description": "Primary color for light theme.",
          "type": "string"
        },
        "primaryOnDark": {
          "description": "Primary color for dark theme.",
          "type": "string"
        },
        "lighterOnLight": {
          "description": "Lighter color than the primary one and for light theme.",
          "type": "string"
        },
        "lighterOnDark": {
          "description": "Lighter color than the primary one and for dark theme.",
          "type": "string"
        },
        "darkerOnLight": {
          "description": "Darker color than the primary one and for light theme.",
          "type": "string"
        },
        "darkerOnDark": {
          "description": "Darker color than the primary one and for dark theme.",
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "logo": {
      "type": "object",
      "properties": {
        "png": {
          "$ref": "#/$defs/url"
        },
        "svg": {
          "$ref": "#/$defs/url"
        }
      },
      "additionalProperties": false
    },
    "image": {
      "type": "object",
      "oneOf": [
        {
          "type": "object",
          "properties": {
            "url": {
              "$ref": "#/$defs/url"
            }
          },
          "additionalProperties": false
        },
        {
          "type": "object",
          "properties": {
            "svg": {
              "type": "string"
            }
          },
          "additionalProperties": false
        },
        {
          "type": "object",
          "properties": {
            "svgImg": {
              "type": "string"
            }
          },
          "additionalProperties": false
        },
        {
          "type": "object",
          "properties": {
            "font": {
              "type": "string"
            }
          },
          "additionalProperties": false
        }
      ]
    },
    "link": {
      "type": "object",
      "required": [
        "url",
        "title",
        "icon"
      ],
      "properties": {
        "url": {
          "$ref": "#/$defs/url"
        },
        "title": {
          "type": "string"
        },
        "icon": {
          "$ref": "#/$defs/image"
        }
      },
      "additionalProperties": false
    },
    "childLinks": {
      "type": "object",
      "required": [
        "title",
        "icon",
        "children"
      ],
      "properties": {
        "title": {
          "type": "string"
        },
        "icon": {
          "type": "object",
          "$ref": "#/$defs/image"
        },
        "children": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/link"
          },
          "minItems": 1
        }
      },
      "additionalProperties": false
    },
    "links": {
      "type": "array",
      "items": {
        "oneOf": [
          {
            "$ref": "#/$defs/link"
          },
          {
            "$ref": "#/$defs/childLinks"
          }
        ]
      },
      "minItems": 4,
      "maxItems": 4,
      "uniqueItems": true
    },
    "isModuleEnabled": {
      "type": "object",
      "required": [
        "governance"
      ],
      "properties": {
        "governance": {
          "type": "boolean"
        }
      },
      "additionalProperties": false
    },
    "semver": {
      "type": "string",
      "minLength": 5,
      "maxLength": 14,
      "pattern": "^(?:0|[1-9]\\d*)\\.(?:0|[1-9]\\d*)\\.(?:0|[1-9]\\d*)$"
    }
  }
}

=== ezstaking/app-registry/public/chains/mainnets/stride/chain.json
{
  "$schema": "../../chain.schema.json",
  "name": "stride",
  "chainName": "Stride",
  "logo_URIs": {
    "png": "https://raw.githubusercontent.com/cosmos/chain-registry/master/stride/images/strd.png",
    "svg": "https://raw.githubusercontent.com/cosmos/chain-registry/master/stride/images/strd.svg"
  },
  "isAConsumerChain": true,
  "providerChain": "cosmoshub",
  "rpcUrl": "https://stride-fleet.main.stridenet.co",
  "restUrl": "https://stride-fleet.main.stridenet.co/api",
  "chainId": "stride-1",
  "bech32": "stride",
  "denom": "strd",
  "denomUpper": "STRD",
  "sdenom": "ustrd",
  "coinType": 118,
  "gasPriceStep": {
    "low": 0.025,
    "average": 0.025,
    "high": 0.025
  },
  "gasModifier": 1.5,
  "coinDecimals": 6,
  "features": ["ibc-transfer", "ibc-go"],
  "coinGeckoId": "stride",
  "chainInfo": {
    "cosmosSdkVersion": "0.47.10",
    "ibcGoVersion": "7.3.1"
  },
  "colors": {
    "primaryOnLight": "#e91179",
    "primaryOnDark": "#e91179",
    "lighterOnLight": "#fef1f7",
    "lighterOnDark": "#fef1f7",
    "darkerOnLight": "#e91179",
    "darkerOnDark": "#e91179"
  },
  "links": [
    {
      "title": "Official Website",
      "url": "https://stride.zone",
      "icon": {
        "svg": "web"
      }
    },
    {
      "title": "Docs",
      "url": "https://docs.stride.zone",
      "icon": {
        "svg": "document"
      }
    },
    {
      "title": "GitHub",
      "url": "https://github.com/Stride-Labs/stride",
      "icon": {
        "svg": "github"
      }
    },
    {
      "title": "Learn more",
      "icon": {
        "svg": "dotsHorizontal"
      },
      "children": [
        {
          "title": "Medium",
          "url": "https://stride.zone/blog",
          "icon": {
            "svg": "medium"
          }
        },
        {
          "title": "Twitter",
          "url": "https://twitter.com/stride_zone",
          "icon": {
            "svg": "twitter"
          }
        },
        {
          "title": "Discord",
          "url": "https://stride.zone/discord",
          "icon": {
            "svg": "discord"
          }
        }
      ]
    }
  ],
  "isExplorerEnabled": true,
  "isModuleEnabled": {
    "governance": true
  },
  "isNativelySupportedByKeplr": true,
  "withCoingeckoApi": true,
  "isFeatured": true
}

=== ezstaking/app-registry/chains/mainnets/sei/chain.json
{
  "$schema": "../../chain.schema.json",
  "name": "sei",
  "chainName": "Sei",
  "logo_URIs": {
    "png": "https://raw.githubusercontent.com/cosmos/chain-registry/master/sei/images/sei.png",
    "svg": "https://raw.githubusercontent.com/cosmos/chain-registry/master/sei/images/sei.svg"
  },
  "rpcUrl": "https://rpc.cosmos.directory/sei",
  "restUrl": "https://rest.cosmos.directory/sei",
  "chainId": "pacific-1",
  "bech32": "sei",
  "denom": "sei",
  "denomUpper": "SEI",
  "sdenom": "usei",
  "coinType": 118,
  "coinDecimals": 6,
  "features": [
    "ibc-transfer"
  ],
  "coinGeckoId": "sei-network",
  "gasPriceStep": {
    "low": 0.02,
    "average": 0.02,
    "high": 0.04
  },
  "chainInfo": {
    "cosmosSdkVersion": "0.45.10",
    "ibcGoVersion": "3.0.0"
  },
  "colors": {
    "primaryOnLight": "#BA364D",
    "primaryOnDark": "#BA364D",
    "lighterOnLight": "#BA364D",
    "lighterOnDark": "#BA364D",
    "darkerOnLight": "#BA364D",
    "darkerOnDark": "#BA364D"
  },
  "links": [
    {
      "title": "Official Website",
      "url": "https://www.sei.io/",
      "icon": {
        "svg": "web"
      }
    },
    {
      "title": "Docs",
      "url": "https://docs.sei.io/",
      "icon": {
        "svg": "document"
      }
    },
    {
      "title": "GitHub",
      "url": "https://github.com/sei-protocol/sei-chain",
      "icon": {
        "svg": "github"
      }
    },
    {
      "title": "Learn more",
      "icon": {
        "svg": "dotsHorizontal"
      },
      "children": [
        {
          "title": "Medium",
          "url": "https://blog.seinetwork.io/",
          "icon": {
            "svg": "medium"
          }
        },
        {
          "title": "Twitter",
          "url": "https://twitter.com/SeiNetwork",
          "icon": {
            "svg": "twitter"
          }
        }
      ]
    }
  ],
  "isExplorerEnabled": true,
  "isModuleEnabled": {
    "governance": true
  },
  "isNativelySupportedByKeplr": false,
  "withCoingeckoApi": false,
  "isFeatured": false
}

=== ezstaking/app-registry/chains/mainnets/desmos/chain.json
{
  "$schema": "../../chain.schema.json",
  "name": "desmos",
  "chainName": "Desmos",
  "logo_URIs": {
    "png": "https://raw.githubusercontent.com/cosmos/chain-registry/master/desmos/images/dsm.png",
    "svg": "https://raw.githubusercontent.com/cosmos/chain-registry/master/desmos/images/dsm.svg"
  },
  "rpcUrl": "https://rpc.mainnet.desmos.network",
  "restUrl": "https://api.mainnet.desmos.network",
  "chainId": "desmos-mainnet",
  "bech32": "desmos",
  "denom": "dsm",
  "denomUpper": "DSM",
  "sdenom": "udsm",
  "coinType": 852,
  "gasPriceStep": {
    "low": 0.001,
    "average": 0.01,
    "high": 0.025
  },
  "coinDecimals": 6,
  "features": [
    "ibc-transfer"
  ],
  "coinGeckoId": "desmos",
  "chainInfo": {
    "cosmosSdkVersion": "0.47.10",
    "ibcGoVersion": "7.3.2"
  },
  "colors": {
    "primaryOnLight": "#d9583f",
    "primaryOnDark": "#d9583f",
    "lighterOnLight": "#ff996e",
    "lighterOnDark": "#ff996e",
    "darkerOnLight": "#ed6c53",
    "darkerOnDark": "#ed6c53"
  },
  "links": [
    {
      "title": "Official Website",
      "url": "https://www.desmos.network",
      "icon": {
        "svg": "web"
      }
    },
    {
      "title": "Docs",
      "url": "https://docs.desmos.network",
      "icon": {
        "svg": "document"
      }
    },
    {
      "title": "GitHub",
      "url": "https://github.com/desmos-labs",
      "icon": {
        "svg": "github"
      }
    },
    {
      "title": "Learn more",
      "icon": {
        "svg": "dotsHorizontal"
      },
      "children": [
        {
          "title": "Medium",
          "url": "https://medium.com/desmosnetwork",
          "icon": {
            "svg": "medium"
          }
        },
        {
          "title": "Twitter",
          "url": "https://twitter.com/DesmosNetwork",
          "icon": {
            "svg": "twitter"
          }
        }
      ]
    }
  ],
  "isExplorerEnabled": true,
  "isModuleEnabled": {
    "governance": true
  },
  "isNativelySupportedByKeplr": false,
  "withCoingeckoApi": false,
  "isFeatured": false
}

=== ezstaking/app-registry/chains/testnets/neutron_testnet/chain.json
{
  "$schema": "../../chain.schema.json",
  "name": "neutron_testnet",
  "chainName": "Neutron Testnet",
  "logo_URIs": {
    "png": "https://raw.githubusercontent.com/cosmos/chain-registry/master/testnets/neutrontestnet/images/neutron-black-logo.png",
    "svg": "https://raw.githubusercontent.com/cosmos/chain-registry/master/testnets/neutrontestnet/images/neutron-black-logo.svg"
  },
  "isAConsumerChain": true,
  "providerChain": "cosmoshub_testnet",
  "rpcUrl": "https://rpc.testcosmos.directory/neutrontestnet",
  "restUrl": "https://rest.testcosmos.directory/neutrontestnet",
  "chainId": "pion-1",
  "bech32": "neutron",
  "denom": "neutron",
  "denomUpper": "NTRN",
  "sdenom": "untrn",
  "coinType": 118,
  "gasPriceStep": {
    "low": 0.025,
    "average": 0.025,
    "high": 0.025
  },
  "coinDecimals": 6,
  "features": [
    "ibc-transfer",
    "cosmwasm"
  ],
  "coinGeckoId": "",
  "assets": [
    {
      "base": "untrn",
      "coingecko_id": null,
      "denom_units": [
        {
          "denom": "ntrn",
          "exponent": 0
        },
        {
          "denom": "untrn",
          "exponent": 6
        }
      ],
      "description": "The native staking and governance token of the ntrn Network.",
      "display": "ntrn",
      "logo_URIs": {
        "png": "https://raw.githubusercontent.com/cosmos/chain-registry/master/testnets/neutrontestnet/images/neutron-black-logo.png",
        "svg": "https://raw.githubusercontent.com/cosmos/chain-registry/master/testnets/neutrontestnet/images/neutron-black-logo.svg"
      },
      "name": "NTRN",
      "symbol": "NTRN"
    }
  ],
  "chainInfo": {
    "cosmosSdkVersion": "0.45.15",
    "ibcGoVersion": "4.3.0"
  },
  "colors": {
    "primaryOnLight": "#000",
    "primaryOnDark": "#fff",
    "lighterOnLight": "#000",
    "lighterOnDark": "#fff",
    "darkerOnLight": "#43ad6b",
    "darkerOnDark": "#43ad6b"
  },
  "links": [
    {
      "title": "Official Website",
      "url": "https://neutron.org",
      "icon": {
        "svg": "web"
      }
    },
    {
      "title": "GitHub",
      "url": "https://github.com/neutron-org",
      "icon": {
        "svg": "github"
      }
    },
    {
      "title": "Twitter",
      "url": "https://twitter.com/Neutron_org",
      "icon": {
        "svg": "twitter"
      }
    },
    {
      "title": "Learn more",
      "icon": {
        "svg": "dotsHorizontal"
      },
      "children": [
        {
          "title": "Discord",
          "url": "https://discord.com/invite/zRT2ZkQsxA",
          "icon": {
            "svg": "discord"
          }
        },
        {
          "title": "Telegram",
          "url": "https://t.me/neutron_community",
          "icon": {
            "svg": "telegram"
          }
        }
      ]
    }
  ],
  "isExplorerEnabled": true,
  "isModuleEnabled": {
    "governance": true
  },
  "isNativelySupportedByKeplr": false,
  "withCoingeckoApi": false,
  "isFeatured": true
}

=== ezstaking/app-registry/chains/mainnets/juno/chain.json
{
  "$schema": "../../chain.schema.json",
  "name": "juno",
  "chainName": "Juno",
  "logo_URIs": {
    "png": "https://raw.githubusercontent.com/cosmos/chain-registry/master/juno/images/juno.png",
    "svg": "https://raw.githubusercontent.com/cosmos/chain-registry/master/juno/images/juno.svg"
  },
  "rpcUrl": "https://rpc.cosmos.directory/juno",
  "restUrl": "https://rest.cosmos.directory/juno",
  "chainId": "juno-1",
  "denom": "juno",
  "denomUpper": "JUNO",
  "sdenom": "ujuno",
  "coinType": 118,
  "gasPriceStep": {
    "low": 0.075,
    "average": 0.1,
    "high": 0.125
  },
  "gasModifier": 1.8,
  "coinDecimals": 6,
  "features": [
    "ibc-transfer",
    "ibc-go",
    "cosmwasm",
    "wasmd_0.24+"
  ],
  "coinGeckoId": "juno-network",
  "chainInfo": {
    "cosmosSdkVersion": "0.47.12",
    "ibcGoVersion": "7.3.1"
  },
  "colors": {
    "primaryOnLight": "#f0827d",
    "primaryOnDark": "#f0827d",
    "darkerOnLight": "#c5585a",
    "darkerOnDark": "#c5585a",
    "lighterOnLight": "#fdf0ef",
    "lighterOnDark": "#fdf0ef"
  },
  "links": [
    {
      "title": "Official Website",
      "url": "https://www.junonetwork.io/",
      "icon": {
        "svg": "web"
      }
    },
    {
      "title": "DApp",
      "icon": {
        "svg": "apps"
      },
      "children": [
        {
          "title": "JunoSwap",
          "url": "https://junoswap.com",
          "icon": {
            "svgImg": "dapp/junoswap"
          }
        },
        {
          "title": "DAODAO",
          "url": "https://daodao.zone/",
          "icon": {
            "svgImg": "dapp/daodao"
          }
        },
        {
          "title": "JunoMint",
          "url": "https://junomint.com/",
          "icon": {
            "svgImg": "dapp/junomint"
          }
        }
      ]
    },
    {
      "title": "Docs",
      "url": "https://docs.junonetwork.io",
      "icon": {
        "svg": "document"
      }
    },
    {
      "title": "Learn more",
      "icon": {
        "svg": "dotsHorizontal"
      },
      "children": [
        {
          "title": "GitHub",
          "url": "https://github.com/CosmosContracts",
          "icon": {
            "svg": "github"
          }
        },
        {
          "title": "Medium",
          "url": "https://medium.com/@JunoNetwork",
          "icon": {
            "svg": "medium"
          }
        },
        {
          "title": "Twitter",
          "url": "https://twitter.com/JunoNetwork",
          "icon": {
            "svg": "twitter"
          }
        }
      ]
    }
  ],
  "isExplorerEnabled": true,
  "isModuleEnabled": {
    "governance": true
  },
  "isNativelySupportedByKeplr": true,
  "withCoingeckoApi": true,
  "isFeatured": true
}

=== ezstaking/app-registry/chains/mainnets/kava/chain.json
{
  "$schema": "../../chain.schema.json",
  "name": "kava",
  "chainName": "Kava",
  "logo_URIs": {
    "png": "https://raw.githubusercontent.com/cosmos/chain-registry/master/kava/images/kava.png",
    "svg": "https://raw.githubusercontent.com/cosmos/chain-registry/master/kava/images/kava.svg"
  },
  "rpcUrl": "https://rpc.data.kava.io",
  "restUrl": "https://api.data.kava.io",
  "chainId": "kava_2222-10",
  "bech32": "kava",
  "denom": "kava",
  "denomUpper": "KAVA",
  "sdenom": "ukava",
  "coinType": 459,
  "coinDecimals": 6,
  "features": [
    "ibc-transfer"
  ],
  "coinGeckoId": "kava",
  "gasPriceStep": {
    "low": 0.05,
    "average": 0.1,
    "high": 0.25
  },
  "chainInfo": {
    "cosmosSdkVersion": "0.47.10",
    "ibcGoVersion": "7.4.0"
  },
  "colors": {
    "primaryOnLight": "#ff564f",
    "primaryOnDark": "#ff564f",
    "lighterOnLight": "#ff564f",
    "lighterOnDark": "#ff564f",
    "darkerOnLight": "#ff564f",
    "darkerOnDark": "#ff564f"
  },
  "links": [
    {
      "title": "Official Website",
      "url": "https://www.kava.io/",
      "icon": {
        "svg": "web"
      }
    },
    {
      "title": "Docs",
      "url": "https://docs.kava.io/docs/intro",
      "icon": {
        "svg": "document"
      }
    },
    {
      "title": "GitHub",
      "url": "https://github.com/kava-labs",
      "icon": {
        "svg": "github"
      }
    },
    {
      "title": "Learn more",
      "icon": {
        "svg": "dotsHorizontal"
      },
      "children": [
        {
          "title": "Medium",
          "url": "https://medium.com/kava-labs",
          "icon": {
            "svg": "medium"
          }
        },
        {
          "title": "Twitter",
          "url": "https://twitter.com/kava_platform",
          "icon": {
            "svg": "twitter"
          }
        }
      ]
    }
  ],
  "isExplorerEnabled": true,
  "isModuleEnabled": {
    "governance": true
  },
  "isNativelySupportedByKeplr": true,
  "withCoingeckoApi": false,
  "isFeatured": false
}

=== ezstaking/app-registry/public/chains/mainnets/mars/chain.json
{
  "$schema": "../../chain.schema.json",
  "name": "mars-protocol",
  "chainName": "Mars Protocol",
  "logo_URIs": {
    "png": "https://raw.githubusercontent.com/cosmos/chain-registry/master/mars/images/mars-token.png",
    "svg": "https://raw.githubusercontent.com/cosmos/chain-registry/master/mars/images/mars-token.svg"
  },
  "rpcUrl": "https://rpc.marsprotocol.io",
  "restUrl": "https://rest.marsprotocol.io",
  "chainId": "mars-1",
  "bech32": "mars",
  "denom": "mars",
  "denomUpper": "MARS",
  "sdenom": "umars",
  "coinType": 118,
  "coinDecimals": 6,
  "features": [
    "ibc-transfer"
  ],
  "coinGeckoId": "mars-protocol",
  "gasPriceStep": {
    "low": 0,
    "average": 0,
    "high": 0.01
  },
  "chainInfo": {
    "cosmosSdkVersion": "0.46.13",
    "ibcGoVersion": "6.1.1"
  },
  "colors": {
    "primaryOnLight": "#DA3A14",
    "primaryOnDark": "#DA3A14",
    "lighterOnLight": "#DA3A14",
    "lighterOnDark": "#DA3A14",
    "darkerOnLight": "#DA3A14",
    "darkerOnDark": "#DA3A14"
  },
  "links": [
    {
      "title": "Official Website",
      "url": "https://www.marsprotocol.io/",
      "icon": {
        "svg": "web"
      }
    },
    {
      "title": "Docs",
      "url": "https://docs.marsprotocol.io",
      "icon": {
        "svg": "document"
      }
    },
    {
      "title": "GitHub",
      "url": "https://github.com/mars-protocol",
      "icon": {
        "svg": "github"
      }
    },
    {
      "title": "Learn more",
      "icon": {
        "svg": "dotsHorizontal"
      },
      "children": [
        {
          "title": "Medium",
          "url": "https://mars-protocol.medium.com/",
          "icon": {
            "svg": "medium"
          }
        },
        {
          "title": "Twitter",
          "url": "https://twitter.com/mars_protocol",
          "icon": {
            "svg": "twitter"
          }
        }
      ]
    }
  ],
  "isExplorerEnabled": true,
  "isModuleEnabled": {
    "governance": true
  },
  "isNativelySupportedByKeplr": true,
  "withCoingeckoApi": false,
  "isFeatured": false
}

=== ezstaking/app-registry/chains/mainnets/quasar/chain.json
{
  "$schema": "../../chain.schema.json",
  "name": "quasar",
  "chainName": "Quasar",
  "logo_URIs": {
    "png": "https://raw.githubusercontent.com/cosmos/chain-registry/master/quasar/images/quasar.png"
  },
  "rpcUrl": "https://rpc.cosmos.directory/quasar",
  "restUrl": "https://rest.cosmos.directory/quasar",
  "chainId": "quasar-1",
  "bech32": "quasar",
  "denom": "qsr",
  "denomUpper": "QSR",
  "sdenom": "uqsr",
  "coinType": 118,
  "coinDecimals": 6,
  "features": [
    "ibc-transfer"
  ],
  "coinGeckoId": "quasar-2",
  "gasPriceStep": {
    "low": 0.1,
    "average": 0.25,
    "high": 0.3
  },
  "chainInfo": {
    "cosmosSdkVersion": "0.50.9",
    "ibcGoVersion": "7.3.2"
  },
  "colors": {
    "primaryOnLight": "#3552F6",
    "primaryOnDark": "#3552F6",
    "lighterOnLight": "#3552F6",
    "lighterOnDark": "#3552F6",
    "darkerOnLight": "#3552F6",
    "darkerOnDark": "#3552F6"
  },
  "links": [
    {
      "title": "Official Website",
      "url": "https://www.quasar.fi/",
      "icon": {
        "svg": "web"
      }
    },
    {
      "title": "Docs",
      "url": "https://docs.quasar.fi/",
      "icon": {
        "svg": "document"
      }
    },
    {
      "title": "GitHub",
      "url": "https://github.com/quasar-finance",
      "icon": {
        "svg": "github"
      }
    },
    {
      "title": "Learn more",
      "icon": {
        "svg": "dotsHorizontal"
      },
      "children": [
        {
          "title": "Medium",
          "url": "https://medium.com/@quasar.fi",
          "icon": {
            "svg": "medium"
          }
        },
        {
          "title": "Twitter",
          "url": "https://twitter.com/quasarfi",
          "icon": {
            "svg": "twitter"
          }
        }
      ]
    }
  ],
  "isExplorerEnabled": true,
  "isModuleEnabled": {
    "governance": true
  },
  "isNativelySupportedByKeplr": true,
  "withCoingeckoApi": false,
  "isFeatured": false
}
